# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    # Standard Go analyzer
    - govet

    # Error checking
    - errcheck

    # Cyclomatic complexity
    - gocyclo

    # Repeated string constants
    - goconst

    # Additional recommended linters
    - ineffassign  # Detects ineffectual assignments
    - staticcheck  # Comprehensive static analysis
    - unused       # Checks for unused constants, variables, functions and types

formatters:
  enable:
    - gofmt        # Standard Go code formatter
    - goimports    # Standard Go imports formatter

linters-settings:
  gocyclo:
    # Minimal cyclomatic complexity to report
    min-complexity: 15

  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimum occurrences to report
    min-occurrences: 3

  errcheck:
    # Report about not checking errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true
    # Report about assignment of errors to blank identifier: `_ = err`
    check-blank: false

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - goconst