package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"runtime/debug"
	"strings"
	"syscall"

	"github.com/spf13/cobra"
	"github.com/tordrt/llmschema"
)

const databaseURLEnv = "DATABASE_URL"

var version string

type cliOptions struct {
	dbURL              string
	outputFile         string
	outputDir          string
	tables             string
	excludeTables      string
	schemaName         string
	omitDatabaseInfo   bool
	omitTableIndex     bool
	preserveStaleFiles bool
}

type extractAndFormatFunc func(context.Context, string, *llmschema.Options, *llmschema.OutputOptions) error

type deferredFileWriter struct {
	path string
	file *os.File
}

func (w *deferredFileWriter) Write(p []byte) (int, error) {
	if w.file == nil {
		file, err := os.Create(w.path)
		if err != nil {
			return 0, fmt.Errorf("failed to create output file: %w", err)
		}
		w.file = file
	}
	return w.file.Write(p)
}

func (w *deferredFileWriter) Close() error {
	if w.file == nil {
		return nil
	}
	return w.file.Close()
}

var rootCmd = newRootCmd(llmschema.ExtractAndFormat)

func newRootCmd(extractAndFormat extractAndFormatFunc) *cobra.Command {
	opts := &cliOptions{}
	cmd := &cobra.Command{
		Use:     "llmschema",
		Short:   "Generate database schema documentation optimized for AI agents",
		Long:    `Generate database schema documentation optimized for AI agents. Extracts schemas from PostgreSQL, MySQL, and SQLite into markdown files that AI assistants can efficiently browse and which humans can easily reference.`,
		Version: displayVersion(),
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return opts.run(cmd, extractAndFormat)
		},
	}

	cmd.Flags().StringVar(&opts.dbURL, "db-url", "", "Database connection string (defaults to DATABASE_URL)")
	cmd.Flags().StringVarP(&opts.outputFile, "output", "o", "", "Output file for the single-file schema (default: stdout)")
	cmd.Flags().StringVarP(&opts.outputDir, "output-dir", "d", "", "Output directory for optional multi-file output")
	cmd.Flags().StringVarP(&opts.tables, "tables", "t", "", "Specific tables (comma-separated, optional)")
	cmd.Flags().StringVarP(&opts.excludeTables, "exclude-tables", "e", "", "Tables to exclude (comma-separated, optional)")
	cmd.Flags().StringVarP(&opts.schemaName, "schema", "s", "", "Database schema name (optional: defaults to 'public' for PostgreSQL, auto-detected from connection string for MySQL)")
	cmd.Flags().BoolVar(&opts.omitDatabaseInfo, "no-database-info", false, "Exclude database type and version from the overview file")
	cmd.Flags().BoolVar(&opts.omitTableIndex, "no-table-index", false, "Exclude the table index from single-file output")
	cmd.Flags().BoolVar(&opts.preserveStaleFiles, "preserve-stale-files", false, "Do not delete table files generated by previous runs")
	cmd.MarkFlagsMutuallyExclusive("output", "output-dir")

	return cmd
}

func (opts *cliOptions) run(cmd *cobra.Command, extractAndFormat extractAndFormatFunc) (err error) {
	databaseURL := opts.dbURL
	if databaseURL == "" {
		databaseURL = os.Getenv(databaseURLEnv)
	}
	if databaseURL == "" {
		return fmt.Errorf("--db-url is required or %s must be set", databaseURLEnv)
	}

	outOpts := &llmschema.OutputOptions{
		OutputDir:          opts.outputDir,
		OmitDatabaseInfo:   opts.omitDatabaseInfo,
		OmitTableIndex:     opts.omitTableIndex,
		PreserveStaleFiles: opts.preserveStaleFiles,
	}

	if opts.outputFile != "" {
		writer := &deferredFileWriter{path: opts.outputFile}
		defer func() {
			err = errors.Join(err, writer.Close())
		}()
		outOpts.Writer = writer
	} else if opts.outputDir == "" {
		outOpts.Writer = cmd.OutOrStdout()
	}

	extractionOpts := &llmschema.Options{
		Tables:        parseTableList(opts.tables),
		ExcludeTables: parseTableList(opts.excludeTables),
		SchemaName:    opts.schemaName,
	}

	return extractAndFormat(cmd.Context(), databaseURL, extractionOpts, outOpts)
}

func displayVersion() string {
	if version != "" {
		return version
	}
	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return "dev"
}

func parseTableList(tablesStr string) []string {
	if tablesStr == "" {
		return nil
	}
	var tableList []string
	for _, table := range strings.Split(tablesStr, ",") {
		table = strings.TrimSpace(table)
		if table != "" {
			tableList = append(tableList, table)
		}
	}
	return tableList
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	if err := rootCmd.ExecuteContext(ctx); err != nil {
		os.Exit(1)
	}
}
